# Generated by Django 6.0.1 on 2026-02-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('pedagogie', '0001_initial'),
        ('structure_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceDelegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu_pd', models.CharField(choices=[('PRESENT', 'P'), ('ABSENT', 'A')], max_length=10)),
                ('delegue_pd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pds', to='comptes.delegue')),
                ('etudiant_pd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pds', to='structure_academique.etudiant')),
                ('seance_pd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pds', to='pedagogie.seance')),
            ],
            options={
                'unique_together': {('etudiant_pd', 'seance_pd')},
            },
        ),
        migrations.CreateModel(
            name='PresenceEmpreinte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_pe', models.TimeField()),
                ('type_pe', models.CharField(choices=[('ENTRER', 'E'), ('SORTIR', 'S')], max_length=10)),
                ('etudiant_pe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pes', to='structure_academique.etudiant')),
                ('seance_pe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pes', to='pedagogie.seance')),
                ('utilisateur_pe', models.ForeignKey(limit_choices_to={'role': 'RESPONSABLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptes.utilisateur')),
            ],
            options={
                'unique_together': {('etudiant_pe', 'seance_pe')},
            },
        ),
        migrations.CreateModel(
            name='PresenceProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statu_pp', models.CharField(choices=[('PRESENT', 'P'), ('ABSENT', 'A')], max_length=10)),
                ('etudiant_pp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pps', to='structure_academique.etudiant')),
                ('professeur_pp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pps', to='comptes.professeur')),
                ('seance_pp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pps', to='pedagogie.seance')),
            ],
            options={
                'unique_together': {('etudiant_pp', 'seance_pp')},
            },
        ),
    ]
