# Generated by Django 6.0.1 on 2026-02-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100)),
                ('prenom_utilisateur', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RESPONSABLE', 'Responsable'), ('PROFESSEUR', 'Professeur'), ('DELEGUE', 'Délégué')], max_length=20)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_responsable', models.CharField(choices=[('DOMAINE', 'Domaine'), ('MENTION', 'Mention'), ('EMPREINTE', 'Empreinte')], max_length=20)),
                ('domaine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to='structure_academique.domaine')),
                ('mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsables', to='structure_academique.mention')),
                ('utilisateur_r', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsables', to='comptes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_p', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professeurs', to='comptes.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Delegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegues', to='structure_academique.etudiant')),
                ('utilisateur_d', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegues', to='comptes.utilisateur')),
            ],
        ),
    ]
