# Generated by Django 6.0.1 on 2026-02-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0001_initial'),
        ('structure_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ue', models.CharField(max_length=150)),
                ('code_ue', models.CharField(max_length=150)),
                ('coefficient', models.IntegerField()),
                ('volume_horaire', models.IntegerField()),
                ('mention_ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='structure_academique.mention')),
                ('niveau_ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='structure_academique.niveau')),
                ('promotion_ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ues', to='structure_academique.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('h_debut', models.TimeField()),
                ('h_fin', models.TimeField()),
                ('professeur_s', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='comptes.professeur')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='pedagogie.ue')),
            ],
        ),
    ]
