# Generated by Django 6.0.1 on 2026-02-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_niveau', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mention', models.CharField(max_length=100, unique=True)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='structure_academique.domaine')),
            ],
            options={
                'unique_together': {('nom_mention', 'domaine')},
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_promotion', models.CharField(max_length=100)),
                ('annee_universitaire', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('nom_promotion', 'annee_universitaire')},
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.IntegerField(unique=True)),
                ('nom_etudiant', models.CharField(max_length=100)),
                ('prenom_etudiant', models.CharField(max_length=100)),
                ('date_de_naissance', models.DateField()),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='structure_academique.mention')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='structure_academique.niveau')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='structure_academique.promotion')),
            ],
        ),
    ]
