# Generated by Django 6.0.1 on 2026-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(max_length=20)),
                ('nom_enseignant', models.CharField(max_length=255)),
                ('prenom_enseigant', models.CharField(max_length=255)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=255)),
                ('nationalite', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('email_enseignant', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=12)),
                ('adresse', models.CharField(max_length=255)),
                ('code_postale', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('matiere_ens', models.CharField(max_length=100)),
                ('statut_ens', models.CharField(max_length=100)),
                ('date_emb', models.DateField()),
                ('class_attr', models.CharField(max_length=100)),
            ],
        ),
    ]
