# Generated by Django 6.0.1 on 2026-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_academique', '0002_enseignant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='class_attr',
            field=models.JSONField(),
        ),
    ]
