# Generated by Django 6.0.1 on 2026-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_academique', '0003_alter_enseignant_class_attr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='prenom_enseigant',
            new_name='prenom_enseignant',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='class_attr',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='email_enseignant',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
