# Generated by Django 6.0.1 on 2026-02-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure_academique', '0004_rename_prenom_enseigant_enseignant_prenom_enseignant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email_etudiant',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
