# Generated by Django 6.0.1 on 2026-02-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure_academique', '0005_etudiant_email_etudiant_etudiant_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='email_etudiant',
        ),
    ]
